JekaShopAdminBundle:
    resource: "@JekaShopAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

JekaTagsBundle:
    resource: "@JekaTagsBundle/Controller/"
    type:     annotation
    prefix:   /

#pages:
#    resource: "@JekaShopBundle/Controller/PagesController.php"
#    type:     annotation
#    prefix:   /pages

JekaCategoryBundle:
    resource: "@JekaCategoryBundle/Controller/"
    type:     annotation
    prefix:   /

JekaImageBundle:
    resource: "@JekaImageBundle/Controller/"
    type:     annotation
    prefix:   /

JekaShopBundle:
    resource: "@JekaShopBundle/Controller/"
    type:     annotation
    prefix:   /shop

ApplicationFixturesBundle:
    resource: "@ApplicationFixturesBundle/Controller/"
    type:     annotation
    prefix:   /

VespolinaFulfillmentBundle:
    resource: "@VespolinaFulfillmentBundle/Resources/config/routing.xml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#default:
#    resource: @DefaultBundle/Resources/config/routing.yml

default:
    resource: "@JekaShopBundle/Controller/FirstpageController.php"
    type: annotation
    prefix:   /

JekaPagesBundle:
    resource: "@JekaPagesBundle/Controller/"
    type:     annotation
    prefix:   /pages

fos_user_security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml

#fos_user_user:
#    resource: @FOSUserBundle/Resources/config/routing/user.xml
#    prefix: /user

#vespolina_product:
#    resource: @VespolinaProductBundle/Resources/config/routing/admin.xml
#    prefix: /admin/products

_imagine:
    resource: .
    type:     imagine