security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        fos_user_provider:
            id: fos_user.user_manager

    firewalls:
        main:
            form_login:
                provider:   fos_user_provider
                check_path: /login_check
                login_path: /login
            logout:     true
            anonymous:  true

    access_control:
        - { path: "/dashboard.*", role: IS_AUTHENTICATED_FULLY }
        - { path: "/.*", role: IS_AUTHENTICATED_ANONYMOUSLY }

fos_user:
    db_driver: mongodb
    firewall_name: main
    encoder:
        iterations: 1
        encode_as_base64: false
        algorithm: sha1
    user_class: Application\UserBundle\Document\User
    group:
        group_class: Application\UserBundle\Document\Group